[package]
name = "weather"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-rt = "2"
paperclip = { version = "0.8", features = ["actix4", "swagger-ui"] }
serde = { version = "1.0", features = ["derive"] }
